### ISSUE TITLE
How to train this aimbot?

### ISSUE THREAD

**Issue by Krohagamer** [milksense/venus#11]
Guys i cant understand how to train it i know that its yolov project, but someone have already trained data for it? Pls help

**Comment by milksense** [comment]
To collect image data for annotating and training use
```python
python venus.py collect_data
```

**Comment by Krohagamer** [comment]
> To collect image data for annotating and training use
> 
> ```python
> python venus.py collect_data
> ```

but i must to put images? or just playing the game when it working?

**Comment by milksense** [comment]
No. This process is automatic.

**Comment by Krohagamer** [comment]
> No. This process is automatic.

Oh ok. thx!
