### ISSUE TITLE
Will this repo have support for PS5 control on PC?

### ISSUE THREAD

**Issue by Root-FTW** [milksense/venus#3]
Will this repo have support for PS5 control on PC?

I play on PC, and the old lunar repo never had PS5 controller support on pc

**Comment by milksense** [comment]
Also no yet at this time

**Comment by ZCban** [comment]
U can use rewasd for any controller and set Key for aimbot on controller Key

**Comment by Root-FTW** [comment]
> U can use rewasd for any controller and set Key for aimbot on controller Key

do you have it configured like this? I bought the most complete version of rewasd but I never knew how to configure it with this script, so I uninstalled rewasd

**Comment by ZCban** [comment]
when you use rewasd you have to set the aimbot's activation key to a key on the controller that key you assign will use the keyboard or mouse instead of controller input, i've tried a few times using that yes it works
or you can also create your own python file with pygame to control the controller like a keyboard or mouse

**Comment by ZCban** [comment]
es.

import pygame
import pyautogui

pygame.init()

j = pygame.joystick.Joystick(0)
j.init()

try:
    while True:
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.JOYBUTTONDOWN:
                if j.get_button(1):
                    print("b")
                    
                elif j.get_button(2):
                    print("x")
                    pyautogui.moveTo(1,1)
            elif event.type == pygame.JOYBUTTONUP:
                print("button released")

except KeyboardInterrupt:
    print("EXITING NOW")
    j.quit()

**Comment by Root-FTW** [comment]
> es.
> 
> import pygame import pyautogui
> 
> pygame.init()
> 
> j = pygame.joystick.Joystick(0) j.init()
> 
> try: while True: events = pygame.event.get() for event in events: if event.type == pygame.JOYBUTTONDOWN: if j.get_button(1): print("b")
> 
> ```
>             elif j.get_button(2):
>                 print("x")
>                 pyautogui.moveTo(1,1)
>         elif event.type == pygame.JOYBUTTONUP:
>             print("button released")
> ```
> 
> except KeyboardInterrupt: print("EXITING NOW") j.quit()

Bro DM

RootFTW on Twitter

**Comment by Root-FTW** [comment]
> es.
> 
> import pygame import pyautogui
> 
> pygame.init()
> 
> j = pygame.joystick.Joystick(0) j.init()
> 
> try: while True: events = pygame.event.get() for event in events: if event.type == pygame.JOYBUTTONDOWN: if j.get_button(1): print("b")
> 
> ```
>             elif j.get_button(2):
>                 print("x")
>                 pyautogui.moveTo(1,1)
>         elif event.type == pygame.JOYBUTTONUP:
>             print("button released")
> ```
> 
> except KeyboardInterrupt: print("EXITING NOW") j.quit()

Can DM? discord:
RootFTW#5990
