### ISSUE TITLE
Update requirements.txt.

### ISSUE THREAD

**Issue by Las-Sys** [milksense/venus#6]
Torch 1.13.1+cu117 is incompatible with the current torchvision being used in requirements.txt. 
![Screenshot 2023-02-03 150505](https://user-images.githubusercontent.com/72946102/216636860-8cb4872d-d1ee-4a9d-8d8f-7d9318406e4f.png)

**Comment by milksense** [comment]
Thanks for opening this issue. Upgraded to latest versions.

Use [fb8cefd](https://github.com/milksense/venus/commit/fb8cefd98d3fcda184c8fe48d510ebb0cfcf692d)
