### ISSUE TITLE
 ERROR: Could not find a version that satisfies the requirement torch (from versions: none) ERROR: No matching distribution found for torch

### ISSUE THREAD

**Issue by Allmight0000** [milksense/venus#8]
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

**Comment by ComputerKWasTaken** [comment]
Install the latest pytorch version manually from their website, it works the same

**Comment by NeoCheats** [comment]
Install python 64bit not 32bit
